### ISSUE TITLE
Failed to buy

### ISSUE THREAD

**Issue by NishiVT** [partydragen/Nameless-Store#13]
[18:10:30 WARN]: java.io.FileNotFoundException: https://www.enderblack.net/index.php?route=/api/v2/MyApiKey/pendingStoreCommands&connection_id=5
[18:10:30 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1993)
[18:10:30 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
[18:10:30 WARN]:        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
[18:10:30 WARN]:        at Nameless-Store.jar//com.partydragen.store.bukkit.Store.sendRequest(Store.java:75)
[18:10:30 WARN]:        at Nameless-Store.jar//com.partydragen.store.bukkit.Store.lambda$0(Store.java:47)
[18:10:30 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101)
[18:10:30 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[18:10:30 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[18:10:30 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[18:10:30 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[18:10:30 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by partydragen** [comment]
You need to use the Official Namelessmc plugin https://www.spigotmc.org/resources/nameless-plugin-for-v2.59032/
